### PR TITLE
Removed menu item for Business Moments

### PR DESCRIPTION
**Pull request by goeran**
Solves: https://app.asana.com/0/1202121266838773/1202029655339366/f

Remove all references to "business moments"
- Remove menu item & route
- Remove Backing code for route
- Remove creating and viewing of Business Moments Adaptor
- Remove data objects in api / stores

### CODE REVIEW

**Comment by pavsaund** [comment]
@goeran Great to remove the menu item from studio, but is there a good reason for not wanting to remove the underlying code as well? ie: valuable pattern coding pattern, or exposing the use of an API? If not I propose remove the business moments code from:
- https://github.com/dolittle/Studio/tree/main/Source/SelfService/Web/businessMoments

Also, we have the ability to add a new Business Moment Adapter when creating a new microservice. Should this also be removed?
image
- https://github.com/dolittle/Studio/tree/main/Source/SelfService/Web/microservice/businessMomentsAdaptor
- https://github.com/dolittle/Studio/blob/af7b09b74345417b43c41f50e166fc38db8cc133/Source/SelfService/Web/microservice/create.tsx#L64
- https://github.com/dolittle/Studio/blob/af7b09b74345417b43c41f50e166fc38db8cc133/Source/SelfService/Web/microservice/create.tsx#L156

**Comment by pavsaund** [comment]
This is blocked by #176

**Comment by pavsaund** [comment]
Just had a chat with @goeran  and the motivation is to be opportunistic and get the ball rolling. As the code affected by the business moment adapter is well-contained we can easily also remove the rest of the code as well.

**Comment by pavsaund** [comment]
@goeran I have updated the PR and removed all references to business moments adapter

**Review by goeran — COMMENTED** [review]
Thanks for helping. I think this looks good.

I think we shall land https://github.com/dolittle/Studio/pull/176 into main before this. When #176 is landed we can merge this into main.

**Comment by pavsaund** [comment]
@goeran: 🚢🇮🇹

**Pull request merged**
