### PR TITLE
Fix direct links with environment not working

### PR DESCRIPTION
**Pull request by pavsaund**
## Summary
Opening direct links to microservices in an environment failed sometimes. The cause of this failure is related to which environment the user has last visited. If the user has last been in "Dev", and the link is pointing to "Prod", it would fail. This information is currently stored in local storage.

This PR introduces a higher-order component that reads the `environment` and `applicationId` parameters from the URL, and overwrites these in the global context, which also updates the value in local storage.

### Fixed

- Fix direct links to environments not working when pointing to another environment than the user last visited

### CODE REVIEW

**Comment by pavsaund** [comment]
I manually approved codeclimate checks.

**Comment by pavsaund** [comment]
Currently failing when clearing local storage and navigating directly to a microservice page.
image

**Comment by freshteapot** [comment]
Future work https://app.asana.com/0/1200181647276434/1201993415401681/f

**Review by freshteapot — APPROVED** [review]
🚢 🇮🇹 

I have seen it work in https://dev.dolittle.studio/.

**Pull request merged**
